linters:
  enable:
  - asciicheck
  - bodyclose
  - dogsled
  - errcheck
  - exhaustive
  - exportloopref
  - godot
  - gofmt
  - gofumpt
  - goimports
  - gomodguard
  - goprintffuncname
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - nolintlint
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - typecheck
  - unparam
  - unused
  - whitespace
  disable:
  - dupl
  - gocritic
  - goerr113
  - funlen
  - gochecknoglobals
  - gocognit
  - goconst
  - gocyclo
  - godox
  - gomnd
  - lll
  - maligned
  - nestif
  - nlreturn
  - noctx
  - testpackage
  - wsl

linters-settings:
  gofumpt:
    extra-rules: true
  misspell:
    locale: US
